contiv/install

cluster/Vagrantfile, install/ansible/Dockerfile, install/ansible/Dockerfile.base, install/ansible/env.json, install/ansible/install.sh, install/ansible/install_swarm.sh, install/ansible/uninstall.sh, install/ansible/uninstall_swarm.sh, install/k8s/install.sh, scripts/release.sh
Also making the docker image smaller and moving out the ansible parts to the tgz file to allow easier customization.
Fixes https://github.com/contiv/install/issues/12
Corresponding ansible PR is https://github.com/contiv/ansible/issues/320
=> Adding cleanup for etcd, docker state

scripts/release.sh
Signed-off-by: Himanshu Raj <rhim@users.noreply.github.com>
=> Release package for 1.0.0-beta.1

README.md, cluster/Vagrantfile, install/ansible/install.sh, install/ansible/install_defaults.sh, install/ansible/install_swarm.sh, install/ansible/uninstall.sh, install/ansible/uninstall_swarm.sh, install/k8s/install.sh, install/k8s/uninstall.sh, scripts/release.sh
Also running shellcheck and cleaning up the shell scripts.
Fixes https://github.com/contiv/install/issues/14 &
https://github.com/contiv/install/issues/9
Additional changes:
Save/restore kube-dns config on install/uninstall.
Don't disable firewall of swarm installations, the ansible scripts open appropriate ports.
=> Adding docs for scripts

README.md, cluster/k8smaster_centos.sh, install/k8s/install.sh
Fixes https://github.com/contiv/ccn/issues/202
=> Add service-cidr option to kubeadm install

scripts/demo-k8s.sh
Signed-off-by: Himanshu Raj <rhim@users.noreply.github.com>
=> Adding default network to Contiv demo vagrant setup

install/ansible/install.sh, install/ansible/uninstall.sh
=> Add separate log files for install runs

scripts/release.sh
Signed-off-by: Himanshu Raj <rhim@users.noreply.github.com>
=> Bump version to 1.0.0-beta.3

scripts/kubeadm_test.sh, scripts/swarm_test.sh
=> Allow release version builds for make release-test-*

scripts/build.sh, scripts/generate-certificate.sh, scripts/kubeadm_test.sh, scripts/release.sh, scripts/swarm_test.sh
This PR formats the scripts to follow best practices.
=> scripts: format scripts

install/k8s/install.sh, install/k8s/uninstall.sh
=> Set k8s install/uninstall scripts to abort on errors and unbound variables

install/ansible/install_swarm.sh
Fixes https://github.com/contiv/install/issues/65
=> Run the install container in host network namespace

README.md, scripts/build.sh
Fixes https://github.com/contiv/install/issues/25
=> Adding README to release bundle and adding k8s ACI install instructions

Makefile, install/ansible/install.sh, install/ansible/uninstall.sh, install/ansible/uninstall_swarm.sh, scripts/get_latest_release.sh
Also chmod the log files we create to allow user to deleted them.
Fixes https://github.com/contiv/ccn/issues/258 and removes the python requests dependency for getting build version (fixes https://github.com/contiv/install/issues/85). Allows user to override BUILD_VERSION as well.
=> Revert to shell script for build version

scripts/build.sh
These changes are needed for the beta.5 release.
=> scripts/build.sh: make changes for 1.0.0-beta.5

scripts/release.sh
#77 introduced an issue which broke the script. This PR fixes that issue. Please accept my apologies for the mistake.
=> scripts/release.sh: fix script by removing quotes

Makefile, cluster/k8s1.4/bootstrap_centos.sh, cluster/k8s1.4/bootstrap_ubuntu.sh, cluster/k8s1.6/bootstrap_centos.sh, cluster/k8s1.6/bootstrap_ubuntu.sh, install/ansible/install_swarm.sh, install/ansible/uninstall_swarm.sh, install/k8s/install.sh, install/k8s/uninstall.sh, scripts/build_image.sh, scripts/kubeadm_test.sh, scripts/swarm_test.sh
=> Added 'shfmt' target to Makefile

README.md, cluster/Vagrantfile
Fixes https://github.com/contiv/ccn/issues/269.
=> Add kubeadm notes to install k8s 1.4

README.md, install/k8s/uninstall.sh
=> Fix k8s paths for uninstall & README

install/k8s/install.sh, install/k8s/uninstall.sh
An earlier version of this PR has already been reviewed by @neelimamukiri.
Closes #82
=> k8s: add liveness checks

scripts/build.sh
This bumps the version to 1.0.0-rc1. I'll merge this right away.
=> scripts/build.sh: bump version to 1.0.0-rc1

scripts/build.sh
This PR bumps the version to 1.0.0.
=> scripts/build.sh: bump version to 1.0.0

cluster/Vagrantfile
Signed-off-by: Gaurav Dalvi <gaurav1424@gmail.com>
=> Adding steps for RHEL related setups

RELEASE.md, scripts/release.sh
This PR makes some changes to the release documentation and to the release script.
The changes made to the release script add some simple sanity checks.
The changes made to the documentation explain what needs to be done in order to make a release.
=> document release process changes

install/k8s/k8s1.4/contiv.yaml, install/k8s/k8s1.6/contiv.yaml
required for k8s network policy in contiv.
=> export k8s config in netmaster to connect to api server.

scripts/build.sh, scripts/release.sh
Fixed a few small issues I discovered when eyeballing the build/release scripts
=> Release script updates

install/ansible/env.json, install/ansible/install.sh, install/ansible/install_swarm.sh, install/ansible/uninstall.sh, install/ansible/uninstall_swarm.sh, scripts/build.sh
https://github.com/contiv/ansible/pull/344 needs to merged before this
=> Added v2plugin install support

scripts/kubeadm_test.sh
Fixes https://github.com/contiv/install/issues/132
=> Adding default gateway to demo

README.md, install/k8s/install.sh
=> k8s,README.md: document infra network options

scripts/build.sh
=> scripts/build.sh: bump version to 1.0.2

install/k8s/k8s1.6/aci_gw.yaml, install/k8s/k8s1.6/contiv.yaml
https://github.com/contiv/install/issues/137
=> Add node selectors for contiv services

install/k8s/install.sh
Fixes https://github.com/contiv/install/issues/146
=> Don't set routing mode for ACI fabric

install/ansible/install.sh, install/ansible/install_swarm.sh, install/ansible/uninstall.sh, install/ansible/uninstall_swarm.sh, scripts/build.sh, scripts/get_latest_release.sh
Fixes https://github.com/contiv/install/issues/150 and
https://github.com/contiv/install/issues/151
=> Remove full build and return errors

install/ansible/Dockerfile, install/ansible/install.sh, install/ansible/uninstall.sh, scripts/build.sh, scripts/release.sh
Fixes the following issues:
https://github.com/contiv/install/issues/162
https://github.com/contiv/install/issues/161
https://github.com/contiv/install/issues/154
https://github.com/contiv/install/issues/149
https://github.com/contiv/install/issues/141
Also add the full installer back (hit another lab setup where
curl to get the netplugin binaries is timing out). Updated
the corresponding release script and the "," fix for env.json issue.
=> Fix install image and other issues

README.md
Signed-off-by: Himanshu Raj <rhim@users.noreply.github.com>
=> Adding clarification around v2plugin install

cluster/docker17/centos_docker_install.sh, cluster/docker17/centos_prep.sh
These scripts will be run by Jenkins when setting up Docker-Swarm using v2plugin (instead of the older "legacy" method.)
=> Initial checkin.  Scripts to prep & install docker for Docker-Swarm + v2plugin.

scripts/get_latest_release.py
Resolving issue : https://github.com/contiv/install/issues/179
Signed-off-by: Gaurav Dalvi <Gaurav.Dalvi@users.noreply.github.com>
=> Adding sys module to get_latest_release.py

scripts/get_latest_release.py
=> scripts/get_latest_release.py: fixed bug where JSON was being improperly accessed

Makefile, cluster/Vagrantfile, cluster/docker17/bootstrap_centos.sh, cluster/docker17/master.sh, install/ansible/env.json, install/ansible/install.sh, install/ansible/uninstall.sh, scripts/vbcleanup.sh
Also adding an extra vboxmanage vm cleanup script for cases where
vagrant destroy is failing.
Removing the verbose script output for ansible installer & uninstaller.
=> Merging v2plugin & contiv-network plugin roles

install/ansible/Dockerfile
Tested locally and building successfully
=> install/ansible/Dockerfile: manually install make and cffi to work around a pip issue (credit: Lance aka @riffraff169)

scripts/build.sh
=> scripts/build.sh: update $contiv_version to "1.1.0-rc.1"

scripts/build.sh
=> Update v2plugin version to 1.1.0-rc.1

.gitignore
=> .gitignore: ignore .cfg_* and .etc_* files resulting from `make demo-*` runs

cluster/Vagrantfile
=> cluster/Vagrantfile: support CONTIV_K8S_VERSION of 1.7.x

install/k8s/install.sh
Also cleanup unused contiv_config variable.
=> Pass user specified cluster store to netmaster/netplugin

install/k8s/install.sh
check these before netctl config, 
1. contiv pod status
2. netplugin REST endpoint
fixes fwdmode errors during install
Signed-off-by: Ranjith <rchirakk@users.noreply.github.com>
=> check pod status  before netctl config,

scripts/build.sh
=> scripts/build.sh: update versions to 1.1.0

install/k8s/install.sh, install/k8s/uninstall.sh
See commit messages for details
=> Fixed install.sh bug and uninstall.sh bug

install/k8s/install.sh
Signed-off-by: Ranjith <rchirakk@users.noreply.github.com>
=> fail installer when contiv pods are not ready.

install/k8s/install.sh
DO NOT MERGE YET.  Going to do a test run in the morning :smile:
=> install/k8s/install.sh: fixed a bug where $? was the result of `set -e` rather than the desired command

install/k8s/install.sh
=> merge for release 1.1.1

scripts/build.sh
Signed-off-by: Ranjith <rchirakk@users.noreply.github.com>
=> update new release version 1.1.1

cluster/docker17/bootstrap_centos.sh, cluster/docker17/centos_prep.sh, cluster/k8s1.4/bootstrap_centos.sh, cluster/k8s1.6/bootstrap_centos.sh, install/k8s/install.sh
=> updates for rel-1.1.1

scripts/build.sh
Signed-off-by: Ranjith <rchirakk@users.noreply.github.com>
=> update version to 1.1.2

Makefile
=> Makefile: use our Github fork of shfmt instead of the one on the author's personal domain

install/k8s/install.sh
Don't die with an error in that case.
=> Not all k8s installs have /etc/kubernetes/admin.conf

scripts/build.sh
=> scripts/build.sh: increment version numbers for 1.1.3 release

scripts/build.sh
This PR bumps the version to 1.1.3.
=> scripts/build.sh: bump version to 1.1.3

install/k8s/install.sh
This reverts commit 079b2c4baf82348a143f1da67f51d6b81733d002.
=> Revert "Unpackaged binaries shouldn't go in /usr/bin"

scripts/build.sh
=> scripts/build.sh: update versions to 1.1.4

scripts/build.sh
Start using pinned versions of ansible for more repeatable builds of
the installer
=> pull specific version of contiv/ansible

scripts/build.sh
=> scripts/build.sh: update contiv_ansible_commit to latest HEAD revision

scripts/build.sh
=> scripts/build.sh: update versions to 1.1.5-cvd.1

scripts/build.sh
=> scripts/build.sh: update versions to 1.1.5

Makefile, scripts/build.sh
- Some trailing whitespace
- Comment wrong for target
- With --fail, curl does not error for non 200 http status
=> whitespace, copy pasta, and curl should fail

scripts/jenkins_cleanup.sh
Jenkins needs jenkins-cleanup.sh from the netplugin repo.
=> Copying jenkins_cleanup.sh to this repo for Jenkins

scripts/build.sh
=> scripts/build.sh: bump versions to 1.1.6

scripts/build.sh
=> scripts/build.sh: update versions to 1.1.6

Makefile
Updates ansible pin to include:
https://github.com/contiv/ansible/pull/381
=> ansible adds fwd_mode v2plugin param

Makefile
=> Correct contiv/ansible default commit

Makefile
=> Bump contiv to 1.1.7

Makefile, scripts/build.sh
=> Expose CONTIV_ACI_GW_VERSION

scripts/build.sh
=> Stop copy ansible repo

cluster/k8s1.6/bootstrap_centos.sh
removed wrong cni package reference
=> also pin kubelet to -0 build for k8s 1.6
