contiv/install

- install/ansible/install.sh
- install/ansible/install_swarm.sh
- install/ansible/uninstall.sh
- scripts/release.sh
With the addition of network mode and fwd mode as command line params,
there is no additional host config required. So reusing the file to
override env vars. This is useful for cases where you want to point to a
private repo - change images names etc as these are currently hardcoded
for a release.
> Allow passing env file as a parameter.

- install/ansible/install.sh
- install/ansible/install_swarm.sh
- install/ansible/uninstall.sh
- install/ansible/uninstall_swarm.sh
- install/genInventoryFile.py
- scripts/release.sh
Fixes #27. Current security group opens all ports between the VMs but not externally. So using external public IP for cluster store does not work. Changing it to use private IP by default and specify the cluster store public IP explicitly with the -s cluster_store option where etcd is accessible using public IP.
scripts/release.sh file change is not directly related, but required due to the box folder deletion.
I've also moved the genInventoryFile.py locally to contiv/install to handle the contiv/demo deprecation.
Tested that provision.sh works with new SG as well as old and that explicitly specifying public IP for the cluster store works as well.
We can further customize this by adding a field for node IP to use for netmaster & etcd for each node in the cfg.yml. I haven't worked on that …
> Fix aws install

- install/ansible/Dockerfile
This PR modifies the Dockerfile to reduce the size of the image. The original size of the image was 220 MB. The new image is only 87.5 MB.
> Dockerfile: uninstall dev tools to shrink image

- cluster/bootstrap_centos.sh
Jenkins hosts are failing this step and it is unnecessary for Vagrant setups.
> Removing firewall disable as Vagrantfile does it

- install/k8s/install.sh
- install/k8s/uninstall.sh
@dojacobs give this a try:
```
git remote add dseevr git@github.com:dseevr/install.git
git fetch dseevr
git checkout -t dseevr/k8s_errors
```
> Set k8s install/uninstall scripts to abort on errors and unbound variables

- cluster/bootstrap_centos.sh
One more attempt at getting to disable firewalld without getting back an ssh error for the case where it is already disabled. Also ntp->ntpd for systemctl.
> Fixing ntpd and return value for the case where firewall is not active

- Makefile
- install/ansible/Dockerfile
- install/ansible/install.sh
- install/ansible/install_swarm.sh
- install/ansible/uninstall.sh
- install/ansible/uninstall_swarm.sh
- install/k8s/install.sh
- scripts/build.sh
- scripts/build_image.sh
This requires escaping the ans_opts variable as the syntax for
ProxyCommand requires a quote. ProxyCommand spec requires ncat to be
installed in the container. So creating a new version of the ansible
container and separating it from the installer build.
Now we can build and release the ansible container separately.
Updating the sed statements for env.json update to handle the case where
there are pre-existing values. This is required to repeat a failed
install.
> Fix 57: Allow specifying ProxyCommand ansible option

- scripts/build.sh
This PR still needs the final netplugin 1.0.0-beta.4 release to be made.
etcd is bumped to 2.3.8.
> scripts/build.sh: prepare changes for beta.4

- scripts/release.sh
This variable is required. The script doesn't currently exit if this variable isn't defined.
> scripts/release: ensure BUILD_VERSION is defined

- scripts/build.sh
- scripts/release.sh
This ensures these mistakes are caught easily. There's no need to spend time investigating issues related to this.
> scripts/{release,build}: check working dir & cd

- README.md
- install/k8s/auth_proxy.yaml
- install/k8s/install.sh
- install/k8s/uninstall.sh
- scripts/build.sh
- scripts/kubeadm_test.sh
- scripts/swarm_test.sh
Removing explicit listen address specification for auth_proxy.
Also fixing the test curl command to avoid curl error messages while testing to see that the auth_proxy started.
Fixes https://github.com/contiv/install/issues/78
> Run installer for k8s with explicit sudo

- cluster/k8s1.4/bootstrap_centos.sh
- cluster/k8s1.6/bootstrap_centos.sh
Failure in the last evaluated command in the "if" is okay here, so we don't want to return its exit code. Return 0 if we get to the end of the script without an error.
> Adding explicit exit 0 to bootstrap scripts

- scripts/build.sh
This is the installer part of the change corresponding to https://github.com/contiv/ansible/commit/6f7fd489bfe605364b6e813fd1728ed21e330178. It adds the ovs rpms & deb files for full install build.
> Adding ovs cache files for full build

- install/k8s/install.sh
Routing needs to be set before creating the infra network.
Tested with `make release-test-kubeadm`
> Adding default params for infra vars

- install/ansible/Dockerfile
The `MAINTAINER` instruction is being deprecated in Docker. This means we should also remove it from our Dockerfiles.
> install/ansible/Dockerfile: remove MAINTAINER

- cluster/Vagrantfile
This tiny PR helps speed up VM provisioning. It's useful when you have to work with this dev/test environment a lot.
> cluster/Vagrantfile: use linked clones

- scripts/build.sh
> scripts/build.sh: added info about why $v2plugin_version variable doesn't default to $contiv_version

- README.md
- install/ansible/install.sh
- install/ansible/uninstall.sh
fixes https://github.com/contiv/install/issues/141
> Update env.json for v2plugin option (-p)

- install/k8s/install.sh
> install/k8s/install.sh: ensure that /var/contiv is created even when a TLS cert is specified

- scripts/get_latest_release.py
- scripts/get_latest_release.sh
> scripts/get_latest_release.py: allow errors to go unhandled instead of returning a default version

- cluster/Vagrantfile
> cluster/Vagrantfile: ensure net.ipv4.ip_forward is set to 1 and warn Debian/Ubuntu users to set their FORWARD policy to ACCEPT

- cluster/docker17/centos_prep.sh
Make sure bzip2 is installed because it's not installed with the Centos image we're using on AWS.
> Install bzip2, if it's not already there (like on AWS).

- install/k8s/install.sh
Currently, running install.sh when an ACI key or TLS cert/key already exist results in `cp` failing and aborting the entire script.
> install/k8s/install.sh: only copy aci.key and cert/key if newer than the existing one

- install/k8s/k8s1.6/contiv.yaml
This also cleans up most of the unused mounts for netmaster & netplugin.
Removing the `-x` flag for netplugin. Lets deal with cleanup/upgrades separately.
This is the first part of HA implementation for Contiv on K8s. TBD is etcd HA - I am still trying to understand/decide whether to go with StatefulSets or use the etcd operator for this.
This resolves https://github.com/contiv/ccn/issues/95 and https://github.com/contiv/ccn/issues/319.
> Merge netmaster and auth_proxy

- install/k8s/install.sh
- existence of aci.key secret is tested before attempting to create it
- existence of contivh1 network is tested before attempting to create it
- copy_unless_identical_paths function added and used to avoid the case where someone specifies the
path of where a key, cert, etc. is copied to during a previous installation.
I setup a `CONTIV_K8S_VERSION=v1.7.0 make demo-kubeadm`, deleted the deployment with `kubectl delete -f contiv.yaml` (leaving the contiv etcd service), then ran `install.sh`.  It works with specifying the same cert/key/ACI key that was used in the previous installation (whether you refer to them in some arbitrary location or wherever they were copied to by the previous installer).
> install/k8s/install.sh: changes to allow running the installer when an installation was done previously

- cluster/Vagrantfile
> cluster/Vagrantfile: set box names on the node config rather than the global config

- install/k8s/k8s1.6/contiv-grafana.yml
Grafana doesn't need RBAC authorization to run in the cluster because it doesn't need to access any of the resources.
> Remove RBAC authorization for grafana

- scripts/get_latest_release.sh
Also, enabled `euo pipefail` and updated the script accordingly.  If the user was running python3, the `python` command would fail and the `demo-*` targets would continue with an empty `$BUILD_VERSION`.
> scripts/get_latest_release.sh: switch to python3-friendly print statement (backwards compatible with python2)

- Makefile
The root cause is due to Makefile always hardcode to spin up
1 master and 1 worker. This PR is to utilize vagrantup.sh to spin
up k8s environment. Whereas vagrantup.sh will take the CONTIV_NODES
and CONTIV_MASTERS which matches the workflow of the Vagrantfile
Signed-off-by: Kahou Lei <kalei@cisco.com>
> Unable to spin up multiple workers for demo-kubeadm cluster

- install/k8s/install.sh
The /usr prefix is for system packaged (rpm, deb, etc) files, not
manually installed ones.  Some systems (e.g. RHEL Atomic) have a
read-only /usr, so on those systems installing to /usr/bin won't
work at all.
> Unpackaged binaries shouldn't go in /usr/bin

- cluster/k8s1.6/bootstrap_centos.sh
Currently, we don't pin k8s version and therefore it will pose
compatability issues.
This ticket is to pin 1.6 folder. We need to pin 1.4 folder instead
and it will be in a separated ticket.
Signed-off-by: Kahou Lei <kalei@cisco.com>
> Pin k8s deployment with 1.6.5

- install/ansible/env.json
The intention of override this env is to provide envrionment vars
in many places of ansible roles (which might be a bad idea), but
force it to use no proxy will ignore whatever has been set on system
level and if there's requirement to do http/https proxy on the host,
it will not be able to reach the internet or other network depends
on the proxy settings. We use use system proxy by default, or override
the proxy settings explicitly if it's required.
> Use system proxy

- scripts/unpack-installer.sh
Utility script for unpacking the installer, and downloading it if it
was missing.  It prefers the full installer over the over-the-internet
installer.
> Add unpack-installer.sh

- scripts/prepare_netplugin_tarball.sh
Adding a script that can be used by the Makefile to either maintain
existing behavior by default (download an existing release), or by
adding environment variables, build netplugin based on a requested
branch.
> Add script to fetch netplugin release or build

- scripts/build.sh
Curl went missing with this commit:
https://github.com/contiv/install/commit/dbe1988c06c9dea190372e72a57bd2b8610d4be7#diff-d99b26f864526f6f8f79861d49deb922L149
> restore lost curl for netplugin release tarball

- cluster/Vagrantfile
This PR pins the Vagrant box to the last known Vagrant box which didn't have a kernel with compressed kernel modules. This is a temporary solution to the compressed kernel module issue.
The environment variable makes it possible to override this as needed. This PR is required to sort out the issues with the CI.
> cluster/Vagrantfile: pin box version & add var

- Makefile
- README.md
- install/ansible/Dockerfile
- install/ansible/install.sh
- install/ansible/install_swarm.sh
- install/ansible/uninstall_swarm.sh
- scripts/build.sh
> pass ansible extra args properly to ansible

- Makefile
- install/ansible/install.sh
- install/ansible/install_swarm.sh
- scripts/build.sh
- scripts/prepare_netplugin_artifacts.sh
Works with:
https://github.com/contiv/ansible/pull/382
env.json now passes a flag to build the v2plugin at install time or
not, and that flag is managed during build.sh based on if
NETPLUGIN_BRANCH is set during build.
All the scripts and resources in netplugin:install/v2plugin are copied
to the install archive's staging directory then into the installer
archive.
renamed prepare_netplugin_tarball.sh to prepare_netplugin_artifacts.sh
because it does more than just prepare a tarball now
Drive-by:
* Bumps the default contiv version to 1.1.7
* v2plugin version defaults to the default contiv version
> Install branch built v2plugin

- install/k8s/install.sh
> install/k8s/install.sh: set a timeout of 1 second on kubectl requests when checking for services to be ready

- Makefile
swarm's etcd on workers should be 127.0.0.1
old code had etcd_proxy listen on all interfaces, #376
removed the ETCD_LISTEN_CLIENT_URLS env var that configured that.
The proxy only listens on 127.0.0.1, but swarm startup script was
pointing to the control interface's IP.
> ansible SHA for legacy swarm etcd url

- install/k8s/install.sh
the second -c was to specify config file but that isn't supported any longer, -c is now for consul
> remove dupe -c flag for install

- cluster/k8s1.8/bootstrap_centos.sh
- cluster/k8s1.8/k8smaster.sh
This PR does the following two things:
1. `kubeadm-1.8.4` installs `kubelet-1.8.4` too. Hence, no need to install `kubelet-1.8.4` separately as it causes the following error when running `make demo-kubeadm`:
```
==> kubeadm-master: ---> Package kubelet.x86_64 0:1.8.4-1 will be installed
==> kubeadm-master: --> Processing Dependency: kubernetes-cni = 0.5.1 for package: kubelet-1.8.4-1.x86_64
==> kubeadm-master: --> Finished Dependency Resolution
==> kubeadm-master:  You could try using --skip-broken to work around the problem
==> kubeadm-master: Error: Package: kubelet-1.8.4-1.x86_64 (kubernetes)
==> kubeadm-master:            Requires: kubernetes-cni = 0.5.1
==> kubeadm-master:            Available: kubernetes-cni-0.3.0.1-0.07a8a2.x86_64 (kubernetes)
==> kubeadm-master: …
```
> Fixed kubelet RPM and kubeadm token expiry issue

- cluster/k8s1.6/bootstrap_centos.sh
upstream packaging failed:
kubernetes/kubernetes#57334
pinning versions for now to get CI working
> fix 1.1 with pinned kubeadm deps
